#include "common.h"
#include "json.h"
#include "openssl.h"
#include "macho.h"
#include "bundle.h"
#include <libgen.h>
#include <dirent.h>
#include <getopt.h>
#include <minizip/miniunz.h>
#include <minizip/zip.h>