name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Discover Env
      run: | 
        ls -la 
        ls -la ${{ github.workspace }}
        ls -la ${{ github.workspace }}/zsign


    - name: Build
      run: chmod +x install.sh && ./install.sh

    - name: Test
      run: ctest

