name: Build & Test (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chmod +x INSTALL.sh
        ./INSTALL.sh

    - name: Set up environment
      run: |
        brew install zip 
        brew install unzip 
        brew install openssl@3 
        brew install cmake

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: zsign-binary
        path: /usr/local/bin/zsign